# Generated by Django 5.2.8 on 2026-02-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_alter_orderitem_order_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
